// GANTI dengan nomor WhatsApp toko: kode negara 62, tanpa tanda + atau spasi.
const NOMOR_WHATSAPP_TOKO = "6282129366190";
const produk = [
{id:"jumbo",nama:"Boneka Unta Jumbo",kategori:"boneka",harga:114000,gambar:"assets/unta-jumbo-info.jpeg",tag:"Favorit",desc:"Boneka unta jumbo dengan pelana merah. Detail bahan dan ukuran ada di foto."},
{id:"l",nama:"Boneka Unta (L)",kategori:"boneka",harga:57000,gambar:"assets/unta-l.png",tag:"Ukuran L",desc:"Boneka unta ukuran L dengan detail pelana khas."},
{id:"m",nama:"Boneka Unta (M)",kategori:"boneka",harga:57000,gambar:"assets/unta-m.png",tag:"Ukuran M",desc:"Boneka unta ukuran sedang untuk hadiah."},
{id:"s",nama:"Boneka Unta (S)",kategori:"boneka",harga:57000,gambar:"assets/unta-s.png",tag:"Ukuran S",desc:"Boneka unta mungil dengan kombinasi warna manis."},
{id:"xl",nama:"Boneka Unta XL",kategori:"boneka",harga:114000,gambar:"assets/unta-xl-info.png",tag:"Ukuran XL",desc:"Foto informasi memuat ukuran, bahan, dan isi boneka."},
{id:"keycamel",nama:"Gantungan Kunci Unta",kategori:"gantungan",harga:13000,gambar:"assets/gantungan-unta.png",tag:"Suvenir",desc:"Gantungan kunci boneka unta mini untuk oleh-oleh."},
{id:"keykabah",nama:"Gantungan Kunci Ka'bah",kategori:"gantungan",harga:13000,gambar:"assets/gantungan-kabah.png",tag:"Suvenir",desc:"Gantungan kunci berbentuk Ka'bah. Detail bahan ada di foto."},
{id:"pillow",nama:"Bantal & Guling Bordir Makkah",kategori:"suvenir",harga:66500,gambar:"assets/bantal-makkah.jpeg",tag:"Dekorasi",desc:"Bantal dan guling bernuansa Makkah untuk suvenir dan dekorasi."}
];
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n).replace(/\u00a0/g," ");
let cart={},filter="semua";
function renderProducts(){document.getElementById("products").innerHTML=produk.filter(p=>filter==="semua"||p.kategori===filter).map(p=>`<article class="product"><div class="photo"><img loading="lazy" src="${p.gambar}" alt="${p.nama}"><span class="tag">${p.tag}</span></div><div class="info"><div class="cat">${p.kategori==="boneka"?"Boneka Unta":p.kategori==="gantungan"?"Gantungan Kunci":"Suvenir Rumah"}</div><h3>${p.nama}</h3><p class="desc">${p.desc}</p><div class="price-row"><span>${money(p.harga)}</span><button class="add" data-add="${p.id}" aria-label="Tambah ke keranjang">+</button></div><div class="tiny">Periksa kembali harga sebelum dipublikasikan.</div></div></article>`).join("")}
function qty(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function renderCart(){document.getElementById("count").textContent=qty();let ids=Object.keys(cart).filter(id=>cart[id]>0);document.getElementById("items").innerHTML=ids.length?ids.map(id=>{let p=produk.find(x=>x.id===id);return `<div class="item"><img src="${p.gambar}" alt=""><div><h4>${p.nama}</h4><b style="font-size:12px;color:#704323">${money(p.harga)}</b><div class="qty"><button data-minus="${id}">−</button>${cart[id]}<button data-plus="${id}">+</button></div></div><button class="remove" data-remove="${id}">Hapus</button></div>`}).join(""):'<div class="empty">Keranjang masih kosong.<br><br>Pilih produk dari katalog.</div>';let total=ids.reduce((s,id)=>s+produk.find(p=>p.id===id).harga*cart[id],0);document.getElementById("total").textContent=money(total);document.getElementById("checkout").disabled=!ids.length;document.getElementById("checkout").style.opacity=ids.length?1:.5}
function openCart(){document.getElementById("backdrop").classList.add("open");renderCart()}function closeCart(){document.getElementById("backdrop").classList.remove("open")}
function toast(t){let el=document.getElementById("toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
document.getElementById("products").addEventListener("click",e=>{let b=e.target.closest("[data-add]");if(!b)return;cart[b.dataset.add]=(cart[b.dataset.add]||0)+1;renderCart();toast("Produk ditambahkan ke keranjang")});
document.getElementById("filters").addEventListener("click",e=>{let b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderProducts()});
document.getElementById("items").addEventListener("click",e=>{let p=e.target.closest("[data-plus]"),m=e.target.closest("[data-minus]"),r=e.target.closest("[data-remove]");if(p)cart[p.dataset.plus]=(cart[p.dataset.plus]||0)+1;if(m)cart[m.dataset.minus]=Math.max(0,(cart[m.dataset.minus]||0)-1);if(r)delete cart[r.dataset.remove];renderCart()});
document.getElementById("openCart").onclick=openCart;document.getElementById("ctaCart").onclick=openCart;document.getElementById("closeCart").onclick=closeCart;document.getElementById("backdrop").addEventListener("click",e=>{if(e.target.id==="backdrop")closeCart()});
function checkout(){let ids=Object.keys(cart).filter(id=>cart[id]>0);if(!ids.length)return;if(NOMOR_WHATSAPP_TOKO.includes("x")){alert("Buka script.js dan ganti NOMOR_WHATSAPP_TOKO dengan nomor WhatsApp toko sebelum pemesanan diaktifkan.");return}let total=0;let lines=ids.map(id=>{let p=produk.find(x=>x.id===id),sub=p.harga*cart[id];total+=sub;return `- ${p.nama} x${cart[id]}: ${money(sub)}`});let text=`Halo HawaPuff, saya ingin memesan:\n${lines.join("\n")}\n\nTotal sementara: ${money(total)}\nMohon info ketersediaan dan ongkir.`;window.open(`https://wa.me/${NOMOR_WHATSAPP_TOKO}?text=${encodeURIComponent(text)}`,"_blank","noopener")}
document.getElementById("checkout").onclick=checkout;document.getElementById("waContact").onclick=e=>{if(NOMOR_WHATSAPP_TOKO.includes("x")){e.preventDefault();alert("Atur nomor WhatsApp toko di script.js terlebih dahulu.")}else{e.preventDefault();window.open(`https://wa.me/${NOMOR_WHATSAPP_TOKO}`,"_blank","noopener")}};
document.getElementById("year").textContent=new Date().getFullYear();renderProducts();renderCart();
